# base image
FROM node:latest

# install required packages
RUN     apt-get update && apt-get install net-tools
RUN     npm update
RUN     npm cache verify && npm cache clean --force
RUN     npm i systeminformation
RUN     npm i express
RUN     npm i request
RUN     npm cache verify && npm cache clean --force
RUN     npm i yargs

RUN mkdir SDCI
WORKDIR SDCI

RUN curl -X GET http://homepages.laas.fr/smedjiah/tmp/gateway.js >> gateway.js
RUN curl -X GET http://homepages.laas.fr/smedjiah/tmp/server.js >> server.js
RUN curl -X GET http://homepages.laas.fr/smedjiah/tmp/device.js >> device.js
