# base image
FROM node:latest

# install required packages
RUN     apt-get update && apt-get install net-tools
RUN     npm update
RUN     npm cache verify && npm cache clean --force
RUN     npm i systeminformation
RUN     npm i express
RUN     npm i request
RUN     npm cache verify && npm cache clean --force
RUN     npm i yargs

RUN mkdir SDCI
WORKDIR SDCI

RUN curl -X GET https://github.com/Thomas-Cnt/sdci/blob/master/scripts/vnf_gi.js

# set entry point for emulator gatekeeper
ENV VIM_EMU_CMD "echo VNF GI at 10.0.0.100 on port 9000"
ENV VIM_EMU_CMD "node vnf_gi.js"
ENV VIM_EMU_CMD_STOP "echo 'Stop VNF GI'"
